=== yodacdr/movasim/MovasimEchov0101/test/carddevkit/cardDevelopmentKit.dtd
<!ELEMENT Settings (RemoteSecurity, GlobalPlatformSecurity, AdminSecurity?)>
<!ATTLIST Settings applicationVersion CDATA #REQUIRED>


<!ELEMENT RemoteSecurity (spiSettings, counter, tar, keys, advancedSettings, remoteConnexion?)>
<!ATTLIST RemoteSecurity format (compact|expandedDefinite|expandedIndefinite) "compact">
<!ATTLIST RemoteSecurity scp02overScp80 (false|true) "false">

<!ELEMENT spiSettings EMPTY>
<!ATTLIST spiSettings spi1 CDATA #REQUIRED>
<!ATTLIST spiSettings spi2 CDATA #REQUIRED>
<!ATTLIST spiSettings kic CDATA #REQUIRED>
<!ATTLIST spiSettings kid CDATA #REQUIRED>

<!ELEMENT counter (#PCDATA)>

<!ELEMENT tar (#PCDATA)>

<!ELEMENT keys (kic?, kid?, kik?, keysFile)>

<!ELEMENT kic (#PCDATA)>

<!ELEMENT kid (#PCDATA)>

<!ELEMENT kik (#PCDATA)>
<!ATTLIST kik type (DES|AES) "DES">

<!ELEMENT keysFile (#PCDATA)>


<!ELEMENT advancedSettings (tpOa, tpPid, tpDcs, tpScts, tsSca)>

<!ELEMENT tpOa (#PCDATA)>
<!ATTLIST tpOa ton CDATA #REQUIRED>

<!ELEMENT tpPid (#PCDATA)>

<!ELEMENT tpDcs (#PCDATA)>

<!ELEMENT tpScts (#PCDATA)>

<!ELEMENT tsSca (#PCDATA)>
<!ATTLIST tsSca ton CDATA #REQUIRED>


<!ELEMENT remoteConnexion (phone, serverIp, (cattpSettings | httpsSettings)?)>
<!ATTLIST remoteConnexion type (SMS|CATTP|HTTPS|APPLET) "SMS">

<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone ton CDATA #REQUIRED>

<!ELEMENT serverIp (#PCDATA)>


<!ELEMENT cattpSettings (bufferSize, bearerDescription, networkAccessName, login, password, otherParameters, cattpBufferSize, cattpId)>

<!ELEMENT bufferSize (#PCDATA)>

<!ELEMENT bearerDescription (bearerType, bearerParameters)>

<!ELEMENT bearerType (#PCDATA)>

<!ELEMENT bearerParameters (#PCDATA)>

<!ELEMENT networkAccessName (#PCDATA)>

<!ELEMENT login (#PCDATA)>
<!ATTLIST login dcs (00|04|08) "04">

<!ELEMENT password (#PCDATA)>
<!ATTLIST password dcs (00|04|08) "04">

<!ELEMENT otherParameters (#PCDATA)>

<!ELEMENT cattpBufferSize (#PCDATA)>

<!ELEMENT cattpId (#PCDATA)>


<!ELEMENT httpsSettings (communicationSettings, connexionParameters, securityParameters, retryPolicyParameters, httpPostParameters)>

<!ELEMENT communicationSettings (aid, pskTls, pskDek, cipherSuite, chunkSize?)>
<!ATTLIST communicationSettings dnsResolver (false|true) "false">

<!ELEMENT aid (#PCDATA)>

<!ELEMENT pskTls (#PCDATA)>

<!ELEMENT pskDek (#PCDATA)>
<!ATTLIST pskDek type (DES|AES) "DES">

<!ELEMENT cipherSuite (#PCDATA)>

<!ELEMENT chunkSize (#PCDATA)>


<!ELEMENT connexionParameters (networkAccessName, login, password, bearerDescription, bufferSize, otherParameters)>


<!ELEMENT securityParameters (pskId, kvn, keyId)>

<!ELEMENT pskId (#PCDATA)>

<!ELEMENT kvn (#PCDATA)>

<!ELEMENT keyId (#PCDATA)>


<!ELEMENT retryPolicyParameters (retryCounter, retryWaitingDelay, retryReportFailure)>

<!ELEMENT retryCounter (#PCDATA)>

<!ELEMENT retryWaitingDelay (hours, minutes, seconds)>

<!ELEMENT hours (#PCDATA)>

<!ELEMENT minutes (#PCDATA)>

<!ELEMENT seconds (#PCDATA)>

<!ELEMENT retryReportFailure (dataDestinationAddress, serviceCentreAddress, errorString)>

<!ELEMENT dataDestinationAddress (#PCDATA)>
<!ATTLIST dataDestinationAddress tonNpi CDATA #REQUIRED>

<!ELEMENT serviceCentreAddress (#PCDATA)>
<!ATTLIST serviceCentreAddress tonNpi CDATA #REQUIRED>

<!ELEMENT errorString (#PCDATA)>


<!ELEMENT httpPostParameters (adminHost, agentId, adminUri)>

<!ELEMENT adminHost (#PCDATA)>

<!ELEMENT agentId (#PCDATA)>

<!ELEMENT adminUri (#PCDATA)>


<!ELEMENT GlobalPlatformSecurity (aid, secureChannelSettings, gpKeys, gpVersionProtocol?)>

<!ELEMENT secureChannelSettings (kvn, keyId)>
<!ATTLIST secureChannelSettings secLevel (00|01|03|11|13|33) "00">

<!ELEMENT gpKeys (enc?, mac?, dek?, keysFile)>

<!ELEMENT enc (#PCDATA)>

<!ELEMENT mac (#PCDATA)>

<!ELEMENT dek (#PCDATA)>

<!ELEMENT gpVersionProtocol (protocol, mode)>
<!ATTLIST gpVersionProtocol gpVersion (211|22) "211">

<!ELEMENT protocol (#PCDATA)>

<!ELEMENT mode (#PCDATA)>


<!ELEMENT AdminSecurity (adm1, aid)>
<!ATTLIST AdminSecurity gpVersion (211|22) "211">

<!ELEMENT adm1 (#PCDATA)>

=== yodacdr/movasim/MovasimEchov0101/test/carddevkit/Movasim_Testing.xml
<?xml version="1.0"?>
<!DOCTYPE Settings SYSTEM "cardDevelopmentKit.dtd">

<!--Card Development Kit - Settings template. Created on 20/07/2021 18:50:40-->

<Settings applicationVersion="2.8.7">
  <RemoteSecurity format="compact">
    <spiSettings spi1="02" spi2="21" kic="55" kid="55" />
    <counter>0000000011</counter>
    <tar>000000</tar>
    <keys>
      <kic>11111111111111112222222222222222</kic>
      <kid>33 33 33 33 33 33 33 33 44 44 44 44 44 44 44 44</kid>
      <keysFile>C:\Program Files (x86)\Valid\Card Development Kit\Claves\Keys.ini</keysFile>
    </keys>
    <advancedSettings>
      <tpOa ton="81">607091100</tpOa>
      <tpPid>7F</tpPid>
      <tpDcs>F6</tpDcs>
      <tpScts>00000000000000</tpScts>
      <tsSca ton="91">34607091100</tsSca>
    </advancedSettings>
  </RemoteSecurity>
  <GlobalPlatformSecurity>
    <aid>A000000151000000</aid>
    <secureChannelSettings secLevel="01">
      <kvn>0</kvn>
      <keyId>1</keyId>
    </secureChannelSettings>
    <gpKeys>
      <enc>11111111111111112222222222222222</enc>
      <mac>33333333333333334444444444444444</mac>
      <dek>33333333333333334444444444444444</dek>
      <keysFile>C:\Program Files (x86)\Valid\Card Development Kit\Claves\Keys.ini</keysFile>
    </gpKeys>
    <gpVersionProtocol gpVersion="211">
      <protocol>02</protocol>
      <mode>55</mode>
    </gpVersionProtocol>
  </GlobalPlatformSecurity>
  <AdminSecurity gpVersion="22">
    <adm1>3132373836333233</adm1>
    <aid>A000000151000000</aid>
  </AdminSecurity>
</Settings>
